apiVersion: v1
kind: Secret
metadata:
  name: mysql-passwords
type: Opaque
data:
  # Replace these with the output from your base64 commands
  DB_PASSWORD: bXlwYXNzd29yZA==
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
